- name: Copying {{COMPONENT}} repo
  ansible.builtin.copy: 
    src : mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: intalling {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enabling {{COMPONENT}} visibility 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting {{COMPONENT}} service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: true

- name: Download and extract {{COMPONENT}} scema  
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Injecting {{COMPONENT}} scema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users

- name: set host name to {{COMPONENT}}-{{ENV}}
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}

