- name: Demo on variable
  hosts: all
  vars:
   url: play.google.com #global variable
  vars_prompt:          #promt variable value will given in the CLI
    - name: username
      prompt: What is your username?
      private: True   #if it is flase the input will be visible 

  tasks:
   - name: printing the variable 
     ansible.builtin.debug:
       msg: The url is {{url}}

   - name: Demo local
     ansible.builtin.debug:
       msg: The local variable is {{URL}}
     vars: 
      URL: local.play.google.com    #local variable have higer periority than global in this task
  
   - name: Demo CLI variable
     ansible.builtin.debug:
      msg: The CLI variable is {{CLIURL}} #undeclared variable will give error. we can give value in the CLI and it have highest periority 
   
   - name: Demo promt varibale
     ansible.builtin.debug:
      msg: The promt varibale is {{username}} 
