- name: Demo on variable
  hosts: all
  vars:
   url: play.google.com #global variable
  tasks:
   - name: printing the variable 
     ansible.builtin.debug:
       msg: The url is {{url}}

   - name: Demo local
     ansible.builtin.debug:
       msg: The local variable is {{URL}}
     vars: 
      URL: local.play.google.com    #local variable have higer periority than global in this task
  
   - name: Demo CLI variable
     ansible.builtin.debug:
      msg: The CLI variable is {{CLIURL}} #undeclared variable will give error. we can give value in the CLI and it have highest periority 

