#to print the facts gatherd by using default variables 

- name: Demo on facts
  hosts: all
  #gather_facts: false flag to enable or disable gathering facts about hosts 
  tasks: 
   - name: printing the default variable  
     ansible.builtin.debug:
       msg: The ansible server flavor is {{ansible_distribution}}

   - name: printing the ssh client by default variable
     ansible.builtin.debug:
       msg: The dns name {{ansible_nodename}} 

   - name: printing the mac address by default variable
     ansible.builtin.debug:
       msg: The mac address of the node is {{ansible_default_ipv4.macaddress}} 