#to print the facts gatherd by using default variables 

- name: Demo on facts
  hosts: all
  tasks: 
   - name: printing the default variable  
     ansible.builtin.debug:
       msg: The ansible server flavor is "{{ansible_distribution}}" 
       
   - name: printing the ssh client by default variable
     ansible.builtin.debug:
       msg: The ssh client is "{{SSH_CLIENT}}"" 
