- name: Demo on conditions 
  hosts: all 
  vars:
    condition: true 
    
  task: 
   - name: print the variable if the variable is true 
     ansible.builtin.debug 
       msg: "{{condition}}"
     when: condition