- name: Demo on conditions 
  hosts: all 
  vars:
    condition: true 

  tasks: 
   - name: printing the variable 
     ansible.builtin.debug:
       msg: The url is {{url}}
     when: condition 
    