- name: Demo on tags 
  hosts: all
  become: true
  tasks:
   - name: intall nginx 
     ansible.builtin.yum:
       name: nginx
       state: present
     tags: install
   - name: start nginx
     ansible.builtin.service:
       name: nginx
       state: started
     tags: start  