- name: Demo on previlaged escalation 
  hosts: all
  tasks: 
   - name: showing the user id 
     ansible.builtin.shell: id    
     register: OUT 
     become: yes  

   - name: printing user id
     ansible.builtin.debug:   
      msg: The uptime of the hosts is {{OUT.stdout}}

   - name: showing the user id 
     ansible.builtin.shell: id    
     register: OUT   

   - name: printing user id
     ansible.builtin.debug:   
      msg: The uptime of the hosts is {{OUT.stdout}}