- name: Demo on loops
  hosts: all

  tasks:
   - name: Register loop output as a variable
     ansible.builtin.debug:
       msg: "{{item}}"
     loop:
       - "one"
       - "two"
     register: OUT
   - name: Register loop output as a variable
     ansible.builtin.shell: "echo {{item}}
     loop:
       - "one"
       - "two"
     register: echo