- name: Demo on packages 
  hosts: all
  become: true   #running as adminsistrator sudo
  tasks:
   - name: intall nginx 
     ansible.builtin.package:
        name: nginx
        state: present
   - name: start nginx
     ansible.builtin.service:
        name: nginx
        state: started 
   - name: stop nginx
     ansible.builtin.service:
        name: nginx
        state: stopped