- name: Demo on packages 
  hosts: all
  become: true   #running as adminsistrator sudo
  
  tasks:
   - name: intall nginx 
     ansible.builtin.packages:
       name: nginx
       state: present
       
   - name: start nginx
     ansible.builtin.service:
       name: nginx
       state: started 