- name: play1
  hosts: all
  become: yes
  tasks:
    - name: Fetches the log file from the remote node 
      ansible.builtin.slurp:
        src: /home/centos/ansible/mysql.log
      register: pwd_log

    - name: Extracting the root password
      ansible.builtin.set_fact:
        DEFAULT_PASSWORD: "{{ pwd_log['content'] | regex_findall('.*temporary password.*')}}"

    - name: printing extracted variable
      ansible.builtin.debug:
         msg: "{{DEFAULT_PASSWORD}}"