- name: Install package
  hosts: all
  become: yes
  tasks:
   - name: installing ngnix
     ansible.builtin.package:
        name: nginx
        state: present
   - name: Start service nginx
     ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
     