- name: Install package
  hosts: all
  become: yes
  tasks:
   - name: installing ngnix
     ansible.builtin.package:
        name: nginx
        state: present
     ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes
