- name: configuring the node js
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: Installing nodejs for {{COMPONENT}} service
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating {{APPUSER}} for {{COMPONENT}} service 
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: app user 

- name: cleaning up {{APPUSER}} user home directory for {{COMPONENT}} service
  ansible.builtin.file:
    path: /home/{{APPUSER}}
    state: absent
  ignore_errors: True  

- name: Download and extract {{COMPONENT}} service  
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copying {{COMPONENT}} file and change permission 
  ansible.builtin.copy: 
    src : /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"

- name: Generating Artifacts npm Install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying {{COMPONENT}} systemd file  
  ansible.builtin.template: 
    src : systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: demon reload and starting the {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: set host name to {{COMPONENT}}-{{ENV}}
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}
