- name: intall nginx 
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and extract front end  
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: cleaning up directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copying frontend file
  ansible.builtin.copy: 
    src : /tmp/frontend-main/static/
    dest: /usr/share/nginx/html 
    remote_src: yes

- name: Copying proxy file
  ansible.builtin.template: 
    src : roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: demon reload and starting the ngnix
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true

- name: Configuring {{COMPONENT}} host name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name