- name: Copying {{COMPONENT}} repo
  ansible.builtin.copy: 
    src : "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Installing {{COMPONENT}} service
  ansible.builtin.package: 
    name : mysql-community-server
    state: present

- name: Demon reload and starting the {{COMPONENT}}
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: true
    daemon_reload: true



