- name: Copying {{COMPONENT}} systemd file  
  ansible.builtin.template: 
    src : systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: demon reload and starting the {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true
    daemon_reload: true